"""Shared-memory transport for isolated RealSense capture.

The writer uses a single-slot seqlock: an odd sequence means a write is in
progress, and an unchanged even sequence brackets a coherent snapshot. Pure
Python cannot provide memory fences, so this relies on x86-TSO on the deployed
robots. If arm64 robots become a target, replace it with a double buffer and a
published index (or add a payload checksum).

This module intentionally imports only the standard library and NumPy. Spawned
capture children import it without pulling hardware dependencies into their
startup path.
"""

from __future__ import annotations

import contextlib
import inspect
import struct
import time
from collections.abc import Mapping
from dataclasses import dataclass
from multiprocessing import get_context, resource_tracker, shared_memory
from typing import Any

import numpy as np
import numpy.typing as npt

REALSENSE_CAPTURE_WIDTH = 640
REALSENSE_CAPTURE_HEIGHT = 480
MAX_FRAME_AGE_S = 0.5
JOIN_TIMEOUT_S = 2.0
OPEN_TIMEOUT_S = 45.0
#: Back-to-back attempts run in microseconds while a write lasts ~1 ms, so
#: these retries mostly fail together; real robustness comes from the caller's
#: 10 x 50 ms staleness loop re-invoking the read.
SEQLOCK_READ_RETRIES = 3

_HEADER = struct.Struct("<QdQd")
_SEQUENCE = struct.Struct("<Q")


@dataclass(frozen=True)
class _FrameLayout:
    """Byte offsets and shapes for one shared colour/depth frame slot."""

    width: int
    height: int

    @property
    def colour_offset(self) -> int:
        """Return the first byte of the RGB8 payload."""
        return _HEADER.size

    @property
    def depth_offset(self) -> int:
        """Return the first byte of the z16 payload."""
        return self.colour_offset + self.height * self.width * 3

    @property
    def intrinsics_offset(self) -> int:
        """Return the first byte of the float32 camera matrix."""
        return self.depth_offset + self.height * self.width * np.dtype(np.uint16).itemsize

    @property
    def nbytes(self) -> int:
        """Return the total shared-memory allocation size."""
        return self.intrinsics_offset + 9 * np.dtype(np.float32).itemsize


@dataclass(frozen=True)
class _FrameSlotSpec:
    """Pickle-safe identity and dimensions for one shared-memory frame slot."""

    name: str
    width: int
    height: int

    @property
    def layout(self) -> _FrameLayout:
        """Return the derived byte layout."""
        return _FrameLayout(self.width, self.height)


@dataclass(frozen=True)
class _FrameSnapshot:
    """One copied, coherent shared-memory frame publication."""

    colour: npt.NDArray[np.uint8]
    depth: npt.NDArray[np.uint16]
    intrinsics: npt.NDArray[np.float32]
    depth_scale: float
    published_s: float
    generation: int


@dataclass(frozen=True)
class _CaptureSpec:
    """Minimal pickle-safe configuration passed to the spawn child."""

    serials: tuple[tuple[str, str], ...]
    depth_fps: int
    slots: tuple[tuple[str, _FrameSlotSpec], ...]
    generation: int
    stop_event: Any


@dataclass(frozen=True)
class _ChildPipeline:
    """One child-owned pipeline with its alignment filter and depth scale."""

    pipeline: Any
    align: Any
    depth_scale: float


class _CaptureProcess:
    """Parent-owned spawn process, Pipe handshake, and shared-memory lifetime."""

    def __init__(
        self,
        serials: Mapping[str, str],
        depth_fps: int,
        *,
        child_entry: Any = None,
        context: Any = None,
        open_timeout_s: float = OPEN_TIMEOUT_S,
    ) -> None:
        self._serials = tuple(serials.items())
        self._depth_fps = depth_fps
        self._child_entry = _child_main if child_entry is None else child_entry
        self._context = context
        self._open_timeout_s = open_timeout_s
        self._process: Any | None = None
        self._conn: Any | None = None
        self._stop_event: Any | None = None
        self._slots: dict[str, tuple[shared_memory.SharedMemory, _FrameSlotSpec]] = {}

    @property
    def is_alive(self) -> bool:
        """Return whether the capture child is currently running."""
        return self._process is not None and bool(self._process.is_alive())

    @property
    def is_open(self) -> bool:
        """Return whether an open cycle owns a child and shared mappings."""
        return self._process is not None

    @property
    def process(self) -> Any | None:
        """Expose the child handle for liveness checks and tests."""
        return self._process

    @property
    def slot_names(self) -> dict[str, str]:
        """Return the autogenerated shared-memory names for the open cycle."""
        return {name: spec.name for name, (_, spec) in self._slots.items()}

    def open(self, generation: int) -> None:
        """Spawn lazily, complete the open handshake, then unlink every name."""
        if self._process is not None:
            return
        context = self._context if self._context is not None else get_context("spawn")
        slots: dict[str, tuple[shared_memory.SharedMemory, _FrameSlotSpec]] = {}
        try:
            for name, _ in self._serials:
                slots[name] = _create_frame_slot()
        except BaseException:
            _unlink_slots(slots)
            _close_slots(slots)
            raise

        try:
            stop_event = context.Event()
            parent_conn, child_conn = context.Pipe()
        except BaseException:
            _unlink_slots(slots)
            _close_slots(slots)
            raise
        spec = _CaptureSpec(
            serials=self._serials,
            depth_fps=self._depth_fps,
            slots=tuple((name, slot_spec) for name, (_, slot_spec) in slots.items()),
            generation=generation,
            stop_event=stop_event,
        )
        try:
            process = context.Process(
                target=self._child_entry,
                args=(child_conn, spec),
                name="yam-realsense-capture",
                daemon=True,
            )
        except BaseException:
            child_conn.close()
            parent_conn.close()
            _unlink_slots(slots)
            _close_slots(slots)
            raise
        try:
            process.start()
        except BaseException:
            child_conn.close()
            parent_conn.close()
            _unlink_slots(slots)
            _close_slots(slots)
            raise
        child_conn.close()
        self._process = process
        self._conn = parent_conn
        self._stop_event = stop_event
        self._slots = slots

        error: BaseException | None = None
        if not parent_conn.poll(self._open_timeout_s):
            error = RuntimeError("timed out opening RealSense capture process")
        else:
            try:
                status, payload = parent_conn.recv()
            except EOFError:
                error = RuntimeError("RealSense capture process exited during open handshake")
            else:
                if status == "error":
                    error = RuntimeError(str(payload))
                elif status != "ready":
                    error = RuntimeError(f"invalid RealSense capture handshake status {status!r}")
        _unlink_slots(self._slots)
        if error is not None:
            self.close()
            raise error

    def read(self, name: str) -> _FrameSnapshot | None:
        """Read one coherent copied snapshot from an open camera slot."""
        shm, spec = self._slots[name]
        return _read_frame(shm, spec)

    def close(self) -> None:
        """Cooperatively stop, then terminate and kill an unresponsive child."""
        if self._process is None:
            return
        process = self._process
        conn = self._conn
        stop_event = self._stop_event
        assert conn is not None and stop_event is not None
        conn.close()
        stop_event.set()
        process.join(timeout=JOIN_TIMEOUT_S)
        if process.is_alive():
            process.terminate()
            process.join(timeout=JOIN_TIMEOUT_S)
        if process.is_alive():
            process.kill()
            process.join(timeout=JOIN_TIMEOUT_S)
        _close_slots(self._slots)
        self._process = None
        self._conn = None
        self._stop_event = None
        self._slots = {}


def _import_rs() -> Any:  # pragma: no cover - real child hardware import
    """Import pyrealsense2 only inside a capture child that needs real hardware."""
    import pyrealsense2 as rs  # type: ignore

    return rs


def _child_main(conn: Any, spec: _CaptureSpec, *, rs_module: Any | None = None) -> None:
    """Own every RealSense pipeline and publish frames until parent shutdown."""
    shms: dict[str, shared_memory.SharedMemory] = {}
    bundles: dict[str, _ChildPipeline] = {}
    ready = False
    try:
        shms = {name: _attach_frame_slot(slot_spec) for name, slot_spec in spec.slots}
        rs = rs_module if rs_module is not None else _import_rs()
        bundles = _open_child_pipelines(rs, spec, shms)
        conn.send(("ready", {"slots": tuple(shms)}))
        ready = True
        _drain_child(conn, spec, bundles, shms)
    except BaseException as exc:
        if not ready:
            with contextlib.suppress(BrokenPipeError, EOFError, OSError):
                conn.send(("error", str(exc)))
    finally:
        for bundle in bundles.values():
            with contextlib.suppress(BaseException):
                bundle.pipeline.stop()
        for shm in shms.values():
            shm.close()
        conn.close()


def _open_child_pipelines(
    rs: Any,
    spec: _CaptureSpec,
    shms: dict[str, shared_memory.SharedMemory],
) -> dict[str, _ChildPipeline]:
    """Resolve and open every requested camera, rolling back partial opens."""
    visible: list[tuple[str, str, str | None]] = []
    for device in rs.context().query_devices():
        serial = str(device.get_info(rs.camera_info.serial_number))
        asic_info = rs.camera_info.asic_serial_number
        asic_serial = str(device.get_info(asic_info)) if device.supports(asic_info) else None
        device_name = str(device.get_info(rs.camera_info.name))
        visible.append((device_name, serial, asic_serial))

    resolved: dict[str, str] = {}
    for name, configured_serial in spec.serials:
        match = next(
            (
                serial
                for _, serial, asic_serial in visible
                if configured_serial in (serial, asic_serial)
            ),
            None,
        )
        if match is None:
            listing = ", ".join(
                f"{device_name} / {serial} / {asic_serial or '<unavailable>'}"
                for device_name, serial, asic_serial in visible
            )
            raise RuntimeError(
                f"cannot find RealSense camera {name} ({configured_serial}); "
                f"visible devices: {listing or 'none'}"
            )
        resolved[name] = match

    resolved_slots: dict[str, tuple[str, str]] = {}
    for name, resolved_serial in resolved.items():
        configured_serial = dict(spec.serials)[name]
        previous = resolved_slots.get(resolved_serial)
        if previous is not None:
            previous_name, previous_configured_serial = previous
            raise RuntimeError(
                f"cannot use RealSense cameras {previous_name} "
                f"({previous_configured_serial}) and {name} ({configured_serial}): "
                f"both resolve to device serial {resolved_serial}; configure each "
                f"slot with a different visible device"
            )
        resolved_slots[resolved_serial] = (name, configured_serial)

    slots = dict(spec.slots)
    bundles: dict[str, _ChildPipeline] = {}
    try:
        for name, serial in resolved.items():
            bundles[name] = _open_child_pipeline(
                rs,
                serial,
                spec.depth_fps,
                slots[name],
                shms[name],
                spec.generation,
            )
    except BaseException:
        for bundle in bundles.values():
            with contextlib.suppress(BaseException):
                bundle.pipeline.stop()
        raise
    return bundles


def _open_child_pipeline(
    rs: Any,
    serial: str,
    depth_fps: int,
    slot_spec: _FrameSlotSpec,
    shm: shared_memory.SharedMemory,
    generation: int,
) -> _ChildPipeline:
    """Open, warm, and return one configured child-owned pipeline."""
    rs_cfg = rs.config()
    rs_cfg.enable_device(serial)
    rs_cfg.enable_stream(
        rs.stream.color,
        slot_spec.width,
        slot_spec.height,
        rs.format.rgb8,
        depth_fps,
    )
    rs_cfg.enable_stream(
        rs.stream.depth,
        slot_spec.width,
        slot_spec.height,
        rs.format.z16,
        depth_fps,
    )
    pipeline = rs.pipeline()
    profile = pipeline.start(rs_cfg)
    try:
        depth_scale = float(profile.get_device().first_depth_sensor().get_depth_scale())
        align = rs.align(rs.stream.color)
        for _ in range(10):
            ok, frames = pipeline.try_wait_for_frames(timeout_ms=1000)
            if not ok:
                time.sleep(0.1)
                continue
            _publish_frameset(
                align.process(frames),
                shm,
                slot_spec,
                depth_scale,
                generation,
            )
            break
        return _ChildPipeline(pipeline, align, depth_scale)
    except BaseException:
        with contextlib.suppress(BaseException):
            pipeline.stop()
        raise


def _drain_child(
    conn: Any,
    spec: _CaptureSpec,
    bundles: dict[str, _ChildPipeline],
    shms: dict[str, shared_memory.SharedMemory],
) -> None:
    """Drain all pipelines, treating a control message or Pipe EOF as shutdown."""
    slots = dict(spec.slots)
    while not spec.stop_event.is_set():
        if _parent_requested_stop(conn):
            return
        for name, bundle in bundles.items():
            if spec.stop_event.is_set() or _parent_requested_stop(conn):
                return
            ok, frames = bundle.pipeline.try_wait_for_frames(timeout_ms=1000)
            if ok:
                _publish_frameset(
                    bundle.align.process(frames),
                    shms[name],
                    slots[name],
                    bundle.depth_scale,
                    spec.generation,
                )


def _parent_requested_stop(conn: Any) -> bool:
    """Return whether the parent sent a control message or closed its Pipe end."""
    try:
        if not conn.poll():
            return False
        conn.recv()
    except (EOFError, BrokenPipeError, OSError):
        pass
    return True


def _publish_frameset(
    aligned: Any,
    shm: shared_memory.SharedMemory,
    slot_spec: _FrameSlotSpec,
    depth_scale: float,
    generation: int,
) -> None:
    """Copy one aligned SDK frameset into its shared-memory slot."""
    depth_frame = aligned.get_depth_frame()
    colour_frame = aligned.get_color_frame()
    if not depth_frame or not colour_frame:
        return
    colour: npt.NDArray[np.uint8] = np.asarray(colour_frame.get_data(), dtype=np.uint8).copy()
    depth: npt.NDArray[np.uint16] = np.asarray(depth_frame.get_data(), dtype=np.uint16).copy()
    intrinsics = colour_frame.profile.as_video_stream_profile().intrinsics
    k_matrix: npt.NDArray[np.float32] = np.array(
        [
            [float(intrinsics.fx), 0.0, float(intrinsics.ppx)],
            [0.0, float(intrinsics.fy), float(intrinsics.ppy)],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float32,
    )
    _write_frame(
        shm,
        slot_spec,
        colour=colour,
        depth=depth,
        intrinsics=k_matrix,
        depth_scale=depth_scale,
        published_s=time.monotonic(),
        generation=generation,
    )


def _create_frame_slot(
    width: int = REALSENSE_CAPTURE_WIDTH,
    height: int = REALSENSE_CAPTURE_HEIGHT,
) -> tuple[shared_memory.SharedMemory, _FrameSlotSpec]:
    """Create a zeroed, stdlib-named shared-memory frame slot."""
    layout = _FrameLayout(width, height)
    shm = shared_memory.SharedMemory(create=True, size=layout.nbytes)
    buffer = _buffer(shm)
    # macOS rounds segments up to the page size, so the live buffer may be
    # longer than requested; zero exactly the layout, never the full buffer.
    buffer[: layout.nbytes] = b"\0" * layout.nbytes
    del buffer
    return shm, _FrameSlotSpec(shm.name, width, height)


def _attach_frame_slot(spec: _FrameSlotSpec) -> shared_memory.SharedMemory:
    """Attach without letting the child resource tracker own the parent's name."""
    parameters = inspect.signature(shared_memory.SharedMemory).parameters
    if "track" in parameters:
        kwargs: dict[str, Any] = {"name": spec.name, "track": False}
        return shared_memory.SharedMemory(**kwargs)
    shm = shared_memory.SharedMemory(name=spec.name)
    resource_tracker.unregister(vars(shm)["_name"], "shared_memory")
    return shm


def _write_frame(
    shm: shared_memory.SharedMemory,
    spec: _FrameSlotSpec,
    *,
    colour: npt.NDArray[np.uint8],
    depth: npt.NDArray[np.uint16],
    intrinsics: npt.NDArray[np.float32],
    depth_scale: float,
    published_s: float,
    generation: int,
) -> None:
    """Publish one frame, leaving an odd sequence behind if copying fails.

    ``published_s`` is stamped from ``time.monotonic()`` by the child. That
    clock is boot-relative and machine-wide on Linux and macOS, which lets the
    parent compare it with its own monotonic clock.
    """
    layout = spec.layout
    buffer = _buffer(shm)
    sequence = _read_sequence(buffer)
    odd_sequence = sequence + 1 if sequence % 2 == 0 else sequence + 2
    _HEADER.pack_into(
        buffer,
        0,
        odd_sequence,
        published_s,
        generation,
        depth_scale,
    )
    colour_view: npt.NDArray[np.uint8] = np.ndarray(
        (layout.height, layout.width, 3),
        dtype=np.uint8,
        buffer=buffer,
        offset=layout.colour_offset,
    )
    colour_view[...] = colour
    del colour_view
    depth_view: npt.NDArray[np.uint16] = np.ndarray(
        (layout.height, layout.width),
        dtype=np.uint16,
        buffer=buffer,
        offset=layout.depth_offset,
    )
    depth_view[...] = depth
    del depth_view
    intrinsics_view: npt.NDArray[np.float32] = np.ndarray(
        (3, 3),
        dtype=np.float32,
        buffer=buffer,
        offset=layout.intrinsics_offset,
    )
    intrinsics_view[...] = intrinsics
    del intrinsics_view
    _SEQUENCE.pack_into(buffer, 0, odd_sequence + 1)
    del buffer


def _read_frame(
    shm: shared_memory.SharedMemory,
    spec: _FrameSlotSpec,
    *,
    retries: int = SEQLOCK_READ_RETRIES,
) -> _FrameSnapshot | None:
    """Copy a coherent publication, or return ``None`` after bounded retries."""
    buffer = _buffer(shm)
    for _ in range(retries):
        sequence, published_s, generation, depth_scale = _HEADER.unpack_from(buffer)
        if sequence == 0 or sequence % 2:
            continue
        colour, depth, intrinsics = _copy_payload(buffer, spec.layout)
        if _read_sequence(buffer) == sequence:
            del buffer
            return _FrameSnapshot(
                colour=colour,
                depth=depth,
                intrinsics=intrinsics,
                depth_scale=depth_scale,
                published_s=published_s,
                generation=generation,
            )
    del buffer
    return None


def _copy_payload(
    buffer: Any, layout: _FrameLayout
) -> tuple[
    npt.NDArray[np.uint8],
    npt.NDArray[np.uint16],
    npt.NDArray[np.float32],
]:
    """Copy payload arrays and release every exported buffer view before return."""
    colour_view: npt.NDArray[np.uint8] = np.ndarray(
        (layout.height, layout.width, 3),
        dtype=np.uint8,
        buffer=buffer,
        offset=layout.colour_offset,
    )
    colour = colour_view.copy()
    del colour_view
    depth_view: npt.NDArray[np.uint16] = np.ndarray(
        (layout.height, layout.width),
        dtype=np.uint16,
        buffer=buffer,
        offset=layout.depth_offset,
    )
    depth = depth_view.copy()
    del depth_view
    intrinsics_view: npt.NDArray[np.float32] = np.ndarray(
        (3, 3),
        dtype=np.float32,
        buffer=buffer,
        offset=layout.intrinsics_offset,
    )
    intrinsics = intrinsics_view.copy()
    del intrinsics_view
    return colour, depth, intrinsics


def _read_sequence(buffer: Any) -> int:
    """Read the seqlock counter without retaining a view over shared memory."""
    return int(_SEQUENCE.unpack_from(buffer)[0])


def _buffer(shm: shared_memory.SharedMemory) -> memoryview:
    """Return the live shared-memory buffer with its optional stub narrowed."""
    buffer = shm.buf
    assert buffer is not None
    return buffer


def _unlink_slots(
    slots: Mapping[str, tuple[shared_memory.SharedMemory, _FrameSlotSpec]],
) -> None:
    """Unlink every shared-memory name, tolerating a partially cleaned set."""
    for shm, _ in slots.values():
        with contextlib.suppress(FileNotFoundError):
            shm.unlink()


def _close_slots(
    slots: Mapping[str, tuple[shared_memory.SharedMemory, _FrameSlotSpec]],
) -> None:
    """Close every parent mapping after all transient NumPy views are gone."""
    for shm, _ in slots.values():
        shm.close()
